# Generated by Django 5.0.6 on 2024-06-22 08:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_biography_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='biography',
            name='author',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.author'),
        ),
    ]
